server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        ddl-auto: update