version: "3.8"

services:
  db:
    image: postgres:12.3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

volumes:
  postgres-data: